#version 430

layout(local_size_x = 16, local_size_y = 16) in;

const int WORKGROUP_SIZE = 16;
const int TILE_SIZE = WORKGROUP_SIZE + 2;

struct Temperature
{
    float heatCapacity;
    float transferCoefficient;
    float value;
};

uniform ivec2 resolution;

layout(std430, binding = 1) readonly restrict buffer TemperatureInputBuffer
{
    Temperature inputTemperatures[];
};

layout(std430, binding = 2) writeonly restrict buffer TemperatureOutputBuffer
{
    Temperature outputTemperatures[];
};

shared Temperature localTile[TILE_SIZE][TILE_SIZE];

void loadTileCell(ivec2 localPosition, ivec2 globalPosition)
{
    globalPosition = clamp(globalPosition, ivec2(0), resolution - 1);

    uint index = globalPosition.x + globalPosition.y * resolution.x;

    localTile[localPosition.y][localPosition.x] = inputTemperatures[index];
}

void main()
{
    ivec2 globalPosition = ivec2(gl_GlobalInvocationID.xy);
    ivec2 localPosition = ivec2(gl_LocalInvocationID.xy);

    if(globalPosition.x >= resolution.x || globalPosition.y >= resolution.y)
    {
        return;
    }

    // Center
    loadTileCell(localPosition + ivec2(1), globalPosition);

    // Handle tile borders
    if (localPosition.x == 0) loadTileCell(ivec2(0, localPosition.y + 1), globalPosition + ivec2(-1, 0));
    else if (localPosition.x == WORKGROUP_SIZE - 1) loadTileCell(ivec2(TILE_SIZE - 1, localPosition.y + 1), globalPosition + ivec2(1, 0));

    if (localPosition.y == 0) loadTileCell(ivec2(localPosition.x + 1, 0), globalPosition + ivec2(0, -1));
    else if (localPosition.y == WORKGROUP_SIZE - 1) loadTileCell(ivec2(localPosition.x + 1, TILE_SIZE - 1), globalPosition + ivec2(0, 1));

    // Handle tile angles
    if (localPosition == ivec2(0, 0)) loadTileCell(ivec2(0, 0), globalPosition + ivec2(-1, -1));
    else if (localPosition == ivec2(WORKGROUP_SIZE - 1, 0)) loadTileCell(ivec2(TILE_SIZE - 1, 0), globalPosition + ivec2(1, -1));
    else if (localPosition == ivec2(0, WORKGROUP_SIZE - 1)) loadTileCell(ivec2(0, TILE_SIZE - 1), globalPosition + ivec2(-1, 1));

    if (localPosition == ivec2(WORKGROUP_SIZE - 1,
                               WORKGROUP_SIZE - 1))
        loadTileCell(
            ivec2(TILE_SIZE - 1, TILE_SIZE - 1),
            globalPosition + ivec2(1, 1));

    barrier();

    Temperature currentCell =
        localTile[localPosition.y + 1]
                 [localPosition.x + 1];

    float accumulatedHeatDelta = 0.0;

    for (int offsetY = -1; offsetY <= 1; offsetY++)
    {
        for (int offsetX = -1; offsetX <= 1; offsetX++)
        {
            if (offsetX == 0 && offsetY == 0)
                continue;

            Temperature neighbour = localTile[localPosition.y + 1 + offsetY][localPosition.x + 1 + offsetX];

            // (c1 * t1 + c2 * t2) / (c1 + c2)
            float equilibriumTemperature =
                (currentCell.heatCapacity * currentCell.value +
                 neighbour.heatCapacity * neighbour.value) /
                (currentCell.heatCapacity +
                 neighbour.heatCapacity);

            accumulatedHeatDelta +=
                (equilibriumTemperature - currentCell.value) *
                currentCell.transferCoefficient;
        }
    }

    // division by 8, but mutliplyting is faster so we multiply by 0.125
    currentCell.value += accumulatedHeatDelta * 0.125;

    uint outputIndex = globalPosition.x + globalPosition.y * resolution.x;

    outputTemperatures[outputIndex] = currentCell;
}